# Generated by Django 5.1.2 on 2024-11-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='current_price',
            new_name='average_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='purchase_price',
        ),
    ]
