# Generated by Django 5.1.2 on 2024-11-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_current_price_portfolio_average_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='last_updated',
        ),
    ]
