# Generated by Django 5.1.2 on 2024-11-18 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_portfolio_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
