# Generated by Django 5.1.2 on 2024-11-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_portfolio_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
