# Generated by Django 5.1.2 on 2024-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_portfolio_stock_name_stocktransaction_stock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='date_added',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='exchange_code_bse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='exchange_code_nse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stock_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stock_symbol',
            field=models.CharField(max_length=20),
        ),
    ]
